(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const s of e.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function r(t){if(t.ep)return;t.ep=!0;const e=n(t);fetch(t.href,e)}})();const u=document.querySelector(".mobile-menu-wrapper"),p=document.querySelector(".burger-menu"),b=document.querySelector(".mobile-menu-close-btn"),g=document.querySelectorAll(".mobile-menu-link"),a=document.getElementById("contactForm"),i=document.querySelector(".submit-button"),h=document.querySelectorAll(".buy-ticket"),S=document.querySelector(".website-year"),m="https://httpbin.org";S.textContent=new Date().getFullYear();k();function l(){u.classList.toggle("is-open"),document.body.classList.toggle("modal-open")}function k(){document.querySelectorAll(".concert-row").forEach(o=>{const n=o.querySelector(".concert-available-tickets"),r=o.querySelector(".buy-ticket");n&&r&&parseInt(n.textContent.trim())<=0&&(r.textContent="Розпродано",r.disabled=!0,r.classList.add("sold-out"),o.style.opacity="0.6",n.textContent="Розпродано",n.style.color="#ff4757",n.style.fontWeight="bold")})}async function L(c){const o=c.target,n=o.closest(".concert-row"),r=n.querySelector(".concert-location").textContent,t=n.querySelector(".concert-date").textContent;n.querySelector(".concert-available-tickets").textContent,o.disabled=!0,o.textContent="Обробляємо...";try{const e={id:crypto.randomUUID().slice(0,10),location:r,datetime:t},s=new URLSearchParams(e).toString(),f=`${m}/get?${s}`,d=await fetch(f,{method:"GET",headers:{Accept:"application/json",ContentType:"application/json"}});if(d.ok){const y=await d.json();console.log("✅Ticket booking successful:",y),alert(`🎫 Квиток успішно заброньовано!

        📍 Концерт: ${e.location}
        📅 Дата: ${e.datetime}
        🎟️ Номер бронювання: #${e.id}`),o.textContent="✅ Заброньовано",o.style.background="#4cd964",o.style.borderColor="#4cd964",o.disabled=!0}else throw new Error("Server responded with an error")}catch(e){console.error("❌ Ticket booking error:",e),alert(`❌ Помилка при бронюванні квитка!
      Деталі помилки: ${e.message}
      Будь ласка, спробуйте пізніше або зв'яжіться з нами:
📧 booking@grymgrim.com
📞 +38 (099) 123-45-6`),o.textContent="Купити квиток",o.disabled=!1}}a.addEventListener("submit",async c=>{c.preventDefault();const o=i.innerHTML;i.disabled=!0,i.innerHTML='Відправляємо... <span class="loading"></span>';const n=new FormData(a),r=Object.fromEntries(n),t=new URLSearchParams(r).toString(),e=`${m}/get?${t}`;try{(await fetch(e,{method:"GET",headers:{Accept:"application/json",ContentType:"application/json"}})).ok&&(console.log(r),alert("Дякуємо! Ваше повідомлення успішно надіслано."),a.reset())}catch(s){console.error("Error:",s),alert("Вибачте, сталася помилка при відправці форми. Спробуйте пізніше.")}finally{i.disabled=!1,i.innerHTML=o}});p.addEventListener("click",l);b.addEventListener("click",l);g.forEach(c=>{c.addEventListener("click",l)});u.addEventListener("click",c=>{c.target===u&&l()});h.forEach(c=>{c.addEventListener("click",L)});
//# sourceMappingURL=index.js.map
